config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "home#index"

  resources :categories, path: "conteudos", only: [:index, :show] do
    get ":id", to: "subjects#show", as: :subject
  end

  resources :upsolving_codeforces, only: [:index]

  get "sobre", to: "about#index", as: :about
end

app/controllers/about_controller.rb
# frozen_string_literal: true

class AboutController < ApplicationController
  before_action do
    config_current_nav(:about)
    config_head_title("Sobre - Code Marathon")
    config_head_description("Explicação sobre o site Code Marathon")
  end

  def index; end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  private
    def config_current_nav(current)
      @current_nav = current
    end

    def not_found(message = "Not Found")
      raise ActionController::RoutingError.new(message)
    end

    def config_head_title(title)
      @head_title = title
    end

    def config_head_description(description)
      @head_description = description
    end
end

app/controllers/categories_controller.rb
# frozen_string_literal: true

class CategoriesController < ApplicationController
  before_action do
    config_current_nav(:contents)
  end

  before_action :load_categories

  def index
    redirect_to category_path(@categories.first.slug)
  end

  def show
    @category = obtain_category(params[:id])
    return not_found("Categoria não existe") if @category.blank?

    config_header(@category)

    @subjects = @category.subjects
  end

  private
    def load_categories
      @categories = CodeMarathonContents::Api::Categories.find_all

      @category_by_slug = {}
      @categories.each do |category|
        @category_by_slug[category.slug] = category
      end
    end

    def obtain_category(slug)
      @category = @category_by_slug[slug]
    end

    def config_header(category)
      config_head_title("#{category.name} - Code Marathon")
      config_head_description("Conteúdos sobre o tema #{category.name} em português (pt-BR) produzido pela comunidade Brasileira.")
    end
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  before_action do
    config_current_nav(:home)
    config_head_title("Code Marathon")
    config_head_description("O Code Marathon é um site onde pessoas interessadas por Maratona de Programação e Olimpíada Brasileira de Informática podem aprender os conteúdos recorrentes nessas competições.")
  end

  def index; end
end

app/controllers/subjects_controller.rb
# frozen_string_literal: true

class SubjectsController < ApplicationController
  before_action do
    config_current_nav(:contents)
  end

  def show
    @category = CodeMarathonContents::Api::Categories.find(
      slug: params[:category_id]
    )
    return not_found("Categoria não existe") if @category.blank?

    @subject = CodeMarathonContents::Api::Subjects.find(
      category_slug: params[:category_id],
      subject_slug: params[:id]
    )
    return not_found("Assunto não existe") if @subject.nil?

    @content = CodeMarathonContents::Api::Contents.find(
      category_slug: @category.slug,
      subject_slug: @subject.slug
    )
    return not_found("Conteúdo não foi escrito") if @content.nil?

    config_header(@category, @subject, @content)
  end

  def config_header(category, subject, content)
    config_head_title("#{subject.name} - #{category.name} - Code Marathon")
    config_head_description("Explicação sobre #{subject.name} em português (pt-BR) produzido pela comunidade Brasileira.")
  end
end

app/controllers/upsolving_codeforces_controller.rb
# frozen_string_literal: true

class UpsolvingCodeforcesController < ApplicationController
  before_action do
    config_current_nav(:upsolving_codeforces)
    config_head_title("Upsolving Codeforces - Code Marathon")
    config_head_description("\"Upsolving Codeforces\" é uma ferramenta que permite avaliar seus últimos contents e verificar quais questões precisam de upsolving na plataforma Codeforces.")
  end

  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/components_helper.rb
# frozen_string_literal: true

module ComponentsHelper
end

app/views/about/index.html.erb
<div class="min-h-screen bg-gray-50 py-8 flex flex-col justify-center relative overflow-hidden lg:py-12">
  <div class="relative w-full px-6 py-12 bg-white shadow-xl shadow-slate-700/10 ring-1 ring-gray-900/5 md:max-w-3xl md:mx-auto lg:max-w-4xl lg:pt-16 lg:pb-28">
    <div class="py-8 bg-white">
      <%= render(AboutComponent.new(
        title: "Code Marathon",
        image_url: image_path("about/logo_code_marathon.png")
      )) do %>
        <p>
          O Code Marathon é um sistema onde pessoas interessadas por 
          Maratona de Programação e Olimpíada Brasileira de Informática 
          podem aprender os conteúdos recorrentes nessas competições
        </p>
        <p>
          Você pode contribuir com conteúdos e questões pelo github. 
          Para isso, acesse o repositório do projeto:
        </p>
        <p class="mt-4 text-center">
          <a href="https://github.com/PauloMiranda98/codemarathon-rails" target="_blank" class="text-white bg-gray-800 hover:bg-gray-900 focus:outline-none focus:ring-4 focus:ring-gray-300 font-medium rounded-full text-sm px-5 py-2.5 mr-2 mb-2 dark:bg-gray-800 dark:hover:bg-gray-700 dark:focus:ring-gray-700 dark:border-gray-700">
            Repositório            
          </a>
        </p>
      <% end %>
    </div>
    <div class="py-8 bg-white">
      <%= render(AboutComponent.new(
        title: "OBI",
        image_url: image_path("about/logo_obi.png")
      )) do %>
        A OBI é uma competição organizada nos moldes das outras 
        olimpíadas científicas brasileiras, como Matemática, Física e 
        Astronomia. O objetivo da OBI é despertar nos alunos o interesse 
        por uma ciência importante na formação básica hoje em dia 
        (no caso, ciência da computação), através de uma atividade que 
        envolve desafio, engenhosidade e uma saudável dose de competição. 
        A organização da OBI está cargo do Instituto de Computação da 
        UNICAMP.
      <% end %>
    </div>
    <div class="py-8 bg-white">
      <%= render(AboutComponent.new(
        title: "Maratona de Programação",
        image_url: image_path("about/logo_maratona.png")
      )) do %>
        A Maratona de Programação é um evento da Sociedade Brasileira 
        de Computação que existe desde o ano de 1996. A Maratona nasceu 
        das competições regionais classificatórias para as finais 
        mundiais do concurso de programação, o International Collegiate 
        Programming Contest, e é parte da regional sulamericana do 
        concurso. Ela se destina a alunos e alunas de cursos de graduação 
        e início de pós-graduação na área de Computação e afins (Ciência 
        da Computação, Engenharia de Computação, Sistemas de Informação, 
        Matemática, etc). A competição promove nos estudantes a 
        criatividade, a capacidade de trabalho em equipe, a busca de 
        novas soluções de software e a habilidade de resolver problemas 
        sob pressão. De ano para ano temos observado que as instituições 
        e principalmente as grandes empresas da área têm valorizado os 
        alunos que participam da Maratona.
      <% end %>
    </div>
  </div>
</div>

app/views/categories/show.html.erb
<div class="min-h-screen bg-gray-50 py-8 flex flex-col relative overflow-hidden lg:py-12">
  <div class="relative w-full px-5 py-5 bg-white shadow-sm shadow-slate-700/10 ring-1 ring-gray-900/5 md:max-w-3xl md:mx-auto lg:max-w-4xl lg:pt-16 lg:pb-28">
    <%= render(TabsComponent.new) do |tabs| %>
      <% @categories.each do |category| %>
        <% tabs.with_tab(
          title: category.name, 
          url: category_path(category.slug), 
          is_active: (category.slug == @category.slug)
        ) %>
      <% end %>
      <% tabs.with_body do %>
        <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-4 py-4 bg-white rounded-lg md:py-8" id="about" role="tabpanel" aria-labelledby="about-tab">
          <% @subjects.each do |subject| %>
            <%= render(SubjectCardComponent.new(
              title: subject.name,
              image_url: asset_path(@category.image),
              obi_frequency: subject.obi_frequency,
              icpc_frequency: subject.icpc_frequency,
              link_url: category_subject_path(@category.slug, subject.slug)
            ))%>
          <% end %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/contents/index.html.erb
<div class="p-12 bg-slate-50">
  <%= render(TabsComponent.new) do |tabs| %>
    <% tabs.with_tab(title: "Introdução", url: "#", is_active: true) %>
    <% tabs.with_tab(title: "Matemática", url: "#") %>
    <% tabs.with_tab(title: "Estrutura de Dados", url: "#") %>

    <% tabs.with_body do %>
      <div class="grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4 p-4 bg-white rounded-lg md:p-8 dark:bg-gray-800" id="about" role="tabpanel" aria-labelledby="about-tab">
        <% (1..16).each do |i| %>
          <%= render(ContentCardComponent.new(
            title: "Transforma Rápida de Furier (FFT)",
            image_url: "https://codemarathon.com.br/img/introduction.png",
            obi_frequency: rand(0..4),
            maratona_frequency: rand(0..4),
            link_url: "#"
          ))%>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>

app/views/home/index.html.erb
<div class="max-w-4xl mx-auto py-6 sm:px-6 lg:px-8">
  <div class="px-6 py-28 sm:px-0 text-center">
    <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Code Marathon</h1>
    <p class="text-center mb-4 text-base font-normal text-gray-500 dark:text-gray-400">
      Seja bem-vind@! O Code Marathon é um sistema onde pessoas interessadas 
      por Maratona de Programação e Olimpíada Brasileira de Informática podem 
      aprender os conteúdos recorrentes nessas competições.
    </p>
    <a href="<%= categories_path %>" class="mt-2 inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
      Quero Aprender
      <svg class="ml-2 -mr-1 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6.253v13m0-13C10.832 5.477 9.246 5 7.5 5S4.168 5.477 3 6.253v13C4.168 18.477 5.754 18 7.5 18s3.332.477 4.5 1.253m0-13C13.168 5.477 14.754 5 16.5 5c1.747 0 3.332.477 4.5 1.253v13C19.832 18.477 18.247 18 16.5 18c-1.746 0-3.332.477-4.5 1.253"></path></svg>
    </a>
    <a href="https://github.com/PauloMiranda98/codemarathon-rails" target="_blank" class="mt-2 inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
      Quero Contribuir
      <svg class="ml-2 -mr-1 w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path></svg>
    </a>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html class="h-full" lang="pt-BR">
  <head>
    <%= render(Analytics::TrackGoogleAnalyticsComponent.new(
      google_analytics_id: ENV["GOOGLE_ANALYTICS_ID"]
    )) %>

    <title><%= @head_title.presence || "Code Marathon" %></title>
    <meta name="description" content="<%= @head_description %>">

    <link rel="icon" href="/favicon.png">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", data: { turbo_track: :reload } %>
    <%= javascript_include_tag "application", data: { turbo_track: :reload }, defer: true %>
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.5.4/dist/flowbite.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.6.0/styles/atom-one-dark.min.css">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.2/dist/katex.min.css" integrity="sha384-bYdxxUwYipFNohQlHt0bjN/LCpueqWz13HufFEV1SUatKs1cm4L6fFgCi1jT643X" crossorigin="anonymous">
  </head>
  <body class="h-full">
    <div class="min-h-full">
      <%= render(NavbarComponent.new(user: nil)) do |nav| %>
        <% nav.with_title do %>
          <a href="/">
            <img class="h-12" src="<%= image_path("logo_white_120.png") %>" alt="Logo Code Marathon">
          </a>
        <% end %>
        <% nav.with_item(
          title: "Início", 
          url: root_path, 
          is_active: @current_nav == :home
        ) %>
        <% nav.with_item(
          title: "Conteúdo", 
          url: categories_path,
          is_active: @current_nav == :contents
        ) %>
        <% nav.with_item(
          title: "Upsolving Codeforces", 
          url: upsolving_codeforces_path, 
          is_active: @current_nav == :problems
        ) %>
        <% nav.with_item(
          title: "Sobre", 
          url: about_path, 
          is_active: @current_nav == :about
        ) %>
      <% end %>
      <main>
        <%= yield %>
      </main>
      <footer class="bg-gray-100 mx-auto w-full max-w-container px-4 sm:px-6 lg:px-8">
        <div class="border-t border-slate-900/5 py-10">
          <img class="mx-auto h-12 w-auto text-slate-900" src="<%= image_path("logo_code_marathon.png") %>" alt="Logo do Code Marathon"/>
          <p class="mt-5 text-center text-sm leading-6 text-slate-700">Code Marathon ©2022</p>
        </div>
      </footer>
    </div>
  </body>
</html>

app/views/layouts/application/_navbar.html.erb
<nav class="bg-gray-800">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex items-center justify-between h-16">
      <div class="flex items-center">
        <div class="flex-shrink-0">
          <img class="h-12" src="logo_white_120.png" alt="Logo Code Marathon">
        </div>
        <div class="hidden md:block">
          <div class="ml-10 flex items-baseline space-x-4">
            <% @nav_items.map do |item| %>
              <a
                key="<%= item[:title] %>"
                href="<%= item[:url] %>"
                <% if item[:is_current].present? %>
                  class="bg-gray-900 text-white px-3 py-2 rounded-md text-sm font-medium"
                  aria-current="page"
                <% else %>
                  class="text-gray-300 hover:bg-gray-700 hover:text-white px-3 py-2 rounded-md text-sm font-medium"
                <% end %>
              >
                <%= item[:title] %>
              </a>
            <% end %>
          </div>
        </div>
      </div>

      <div class="hidden md:block">
        <div class="ml-4 flex items-center md:ml-6">
          <!-- Profile dropdown -->
          <div class="ml-3 relative">
            <div>
              <button type="button" class="max-w-xs bg-gray-800 rounded-full flex items-center text-sm focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" id="user-menu-button" aria-expanded="false" aria-haspopup="true">
                <span class="sr-only">Open user menu</span>
                <img class="h-8 w-8 rounded-full" src="without_user.png" alt="">
              </button>
            </div>

            <!--
              Dropdown menu, show/hide based on menu state.
              Entering: "transition ease-out duration-100"
                From: "transform opacity-0 scale-95"
                To: "transform opacity-100 scale-100"
              Leaving: "transition ease-in duration-75"
                From: "transform opacity-100 scale-100"
                To: "transform opacity-0 scale-95"
            -->
            <div class="transform opacity-0 scale-95 origin-top-right absolute right-0 mt-2 w-48 rounded-md shadow-lg py-1 bg-white ring-1 ring-black ring-opacity-5 focus:outline-none" role="menu" aria-orientation="vertical" aria-labelledby="user-menu-button" tabindex="-1">
              <!-- Active: "bg-gray-100", Not Active: "" -->
              <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-0">Seu Perfil</a>
              <a href="#" class="block px-4 py-2 text-sm text-gray-700" role="menuitem" tabindex="-1" id="user-menu-item-2">Sair</a>
            </div>
          </div>
        </div>
      </div>

      <div class="-mr-2 flex md:hidden">
        <!-- Mobile menu button -->
        <button type="button" data-collapse-toggle="mobile-menu" class="bg-gray-800 inline-flex items-center justify-center p-2 rounded-md text-gray-400 hover:text-white hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-offset-gray-800 focus:ring-white" aria-controls="mobile-menu" aria-expanded="false">
          <span class="sr-only">Open main menu</span>
          <!--
            Heroicon name: outline/menu
            Menu open: "hidden", Menu closed: "block"
          -->
          <svg class="hidden h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M4 6h16M4 12h16M4 18h16" />
          </svg>
          <!--
            Heroicon name: outline/x
            Menu open: "block", Menu closed: "hidden"
          -->
          <svg class="block h-6 w-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" aria-hidden="true">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18L18 6M6 6l12 12" />
          </svg>
        </button>
      </div>
    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div class="md:hidden" id="mobile-menu">
    <div class="px-2 pt-2 pb-3 space-y-1 sm:px-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->

      <% @nav_items.map do |item| %>
        <a
          key="<%= item[:title] %>"
          href="<%= item[:url] %>"
          <% if item[:is_current].present? %>
            class="bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium"
            aria-current="page"
          <% else %>
            class="text-gray-300 hover:bg-gray-700 hover:text-white block px-3 py-2 rounded-md text-base font-medium"
          <% end %>
        >
          <%= item[:title] %>
        </a>
      <% end %>
    </div>
    <div class="pt-4 pb-3 border-t border-gray-700">
      <div class="flex items-center px-5">
        <div class="flex-shrink-0">
          <img class="h-10 w-10 rounded-full" src="without_user.png" alt="">
        </div>
        <div class="ml-3">
          <div class="text-base font-medium leading-none text-white">Paulo Miranda</div>
          <div class="text-sm font-medium leading-none text-gray-400">paulo.miranda@codemarathon.com.br</div>
        </div>
      </div>
      <div class="mt-3 px-2 space-y-1">
        <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700">Meu Perfil</a>
        <a href="#" class="block px-3 py-2 rounded-md text-base font-medium text-gray-400 hover:text-white hover:bg-gray-700">Sair</a>
      </div>
    </div>
  </div>
</nav>

app/views/subjects/show.html.erb
<div class="min-h-screen bg-gray-50 py-8 flex flex-col justify-center relative overflow-hidden lg:py-12">
  <%= render(BreadcrumbComponent.new) do |breadcrumb| %>
    <% breadcrumb.with_item(title: "Início", url: root_path) %>
    <% breadcrumb.with_item(title: @category.name, url: category_path(@category.slug)) %>
    <% breadcrumb.with_item(title: @subject.name) %>
  <% end %>
  <div class="my-2"></div>
  <div class="relative w-full px-6 py-12 bg-white shadow-xl shadow-slate-700/10 ring-1 ring-gray-900/5 md:max-w-3xl md:mx-auto lg:max-w-4xl lg:pt-16 lg:pb-28">
    <%= render(MarkdownWithLatexComponent.new(text: @content.text))%>

    <div class="flex justify-center">
      <a href="https://github.com/PauloMiranda98/codemarathon-rails/blob/main/engines/code_marathon_contents/contents/<%= params[:category_id]%>/<%= params[:id] %>.md" target="_blank" class="mt-2 inline-flex justify-center items-center py-3 px-5 text-base font-medium text-center text-white bg-blue-700 rounded-lg hover:bg-blue-800 focus:ring-4 focus:ring-blue-300 dark:focus:ring-blue-900">
        Contribuir com esse conteúdo no GitHub
        <svg class="ml-2 -mr-1 w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z"></path></svg>
      </a>
    </div>
  </div>
</div>

app/views/upsolving_codeforces/index.html.erb
<div class="min-h-screen bg-gray-50 py-8 flex flex-col relative overflow-hidden lg:py-12">
  <div class="relative w-full px-5 py-5 bg-white shadow-sm shadow-slate-700/10 ring-1 ring-gray-900/5 md:max-w-3xl md:mx-auto lg:max-w-4xl lg:pt-16 lg:pb-28">
    <div id="upsolving-codeforces-component"></div>
  </div>
</div>